##########################
MYHOME=/share/data/sharker
##########################
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi
source ~/.bashcolor
source ~/.bashprompt
COMPILERDIR=$MYHOME/share/compilers
COMPILER=gcc-4.9.0
PATH=$COMPILERDIR/$COMPILER/bin:$PATH
export COMPILERDIR COMPILER PATH MYHOME
cd $MYHOME
